### ISSUE TITLE
RGB images

### ISSUE THREAD

**Issue by jiangyuanlin01** [tanveer-hussain/EfficientSOD2#1]
How to train a model using RGB images

**Comment by tanveer-hussain** [comment]
Hello, you can change/remove the following lines in PASModel.py, hopefully it'll work, please let me know if you're not able to do it, I'll create another file for RGB data.

Remove line 56 ~ 63
Change line 102 as > def forward(self, x)
Remove line 108 and 111
Change line 136 as > conv4_feat = self.conv1_11(torch.cat((conv4_feat,conv4_feat_x4),1))


In the training file line 72, just ignore the depth data or you can change the data loader to RGB data
for i, (images, _, _, _, gts, _) in enumerate(train_loader, start=1)
In training file line 78 as > x_sal = PASNet.forward(images)


Apply the same training changes in the testing file.

**Comment by Elliot696** [comment]
in PSAModel.py，you remove line56-63 that remove the definition of self.dpt_model and in line107 the code use the dpt_model.
This cause an error.
