### ISSUE TITLE
About the RGB version of your code

### ISSUE THREAD

**Issue by Sssssuperior** [tanveer-hussain/EfficientSOD2#2]
hello, thanks for your great work.
Would you mind providing your pre-trained model of your RGB and RGB-D code and the RGB version of your code? 
Thank you!

**Comment by tanveer-hussain** [comment]
Hi thank you for the appreciation.

Surely, I'll upload it on Google Drive and share the link on the same page. 

Hopefully, I'll have done it by the end of the next week. Let me know if you don't find it by the next week.

Thanks.

**Comment by peenwin** [comment]
Hello, your paper and code writing is very good, may I ask, can you provide RGB model, training code and test code? thank you.

**Comment by EliaFantini** [comment]
Hi, I would be interested in the pretrained model as well, where di you share the link to google drive? Thanks!

**Comment by tanveer-hussain** [comment]
Hello all,

Please use the link below for pretrained models, sorry for the delay.

https://drive.google.com/drive/folders/10Kli6YeKPfIogP35yia8bu1l6zo-ggol?usp=sharing
