### ISSUE TITLE
I want to reproduce your paper results but can't be sure what dataset that you used.

### ISSUE THREAD

**Issue by LitterMa-820** [tanveer-hussain/EfficientSOD2#3]
I tried some dataset that you mentioned in your paper and readme, but these datasets don't accord with your code.
Your code is like this:
rgbd_datasets = ["DUT-RGBD", 'SIP', "NLPR_TRAIN", 'NJU2K_TRAIN']
but the links you give (including D3Net and UCNet) don't all match.

Could you offer me the datasets that you trained PASNet in your paper?
Finally, it would be even better if the trained model files can be uploaded for comparison.
Thank you!

**Comment by tanveer-hussain** [comment]
Actually the link provided for D3Net is a webpage for saliency detection and you can find these datasets from there.
But I think in the updated version, the authors may have removed some of the datasets or the splits such as training and testing. If you're unable to find the datasets that I've used, please let me know, I'll upload them on drive for you.

Please use the following link to download some of the trained models for DUT-RGBD and SIP with epoch numbers.
https://drive.google.com/drive/folders/10Kli6YeKPfIogP35yia8bu1l6zo-ggol?usp=sharing
